# Introduction to Data Science
## Homework 1: Due Midnight, March 4th. 1/3 of a Grade Deducted for each day late

Student Name: Monil Shah

Student Netid: mds747
***

### Part 1: Case study
- Read [this article](http://www.nytimes.com/2012/02/19/magazine/shopping-habits.html) in the New York Times.
- Use what we've learned in class and from the book to describe how one could set Target's problem up as a predictive modeling problem, such that they could have gotten the results that they did.  Formulate your solution as a proposed plan using our data science terminology.  Include all the aspects of the formulation that you see as relevant to solving the problem.  Be precise but concise.


Ans):
The article deals about the Target using predictive modelling as apart of their marketing strategy. The sample provided here has a varied data about the customers at Target. The data includes customer ID, Guest Id, demographic details (age, sex, location,etc) , credit card details ,  buying details , frequency details, etc . The target as mentioned in the article is to predict whether the female customer is pregnant or not and on basis of prediction to provide specific targeted advertisements and coupons.

The important features in the data are Guest ID, buyer frequency, age, sex, buy_interval , items_last_buytime , visit_frequency , products_bought. The target variable is 'isPregnant'. 

We need to segment customers into subgroups which are similar in terms of target variable 'isPregnant' values. The subgroups are formed on basis of the variables avaiable in the data. The values of variables may be common in subgroup but differ among different subgroups.
The values of variables for cases for cases which target variable is not observed , can be used to know about segments to make predictions. Hence, assigning a new customer to similar subgroup is possible.

Our target variable can be considered as binary(Yes/No) . So as to construct a predictive model. We can segment the customers on basis of variables or attributes into less impure subgroups. The entropy using each attribute is calculated to decide the attribute to form less impure subgroup. The information gain is calculated on the basis of entropy. The customers are segmented further more using information gain to create lesser impure subsets. The values for the target variable is predicted on basis of this model. Thus as mentioned above a Decision tree predictive model can be used to solve the Target's Problem. Once the values are predicted the resultes are crossvalidated and tested.

### Part 2: Dealing with messy data
Not all data you will deal with is going to be clean. In fact, much of it will be very messy! For example, we have the HTML page that lists the contributors to Facebook's [osquery](https://github.com/facebook/osquery) project that is hosted on [Github.com](https://github.com). In this case, all we are interested in are the contributors and how many commits each of them has. Given the HTML page in `"data/osquery_contributors.html"` you will sift through tons of irrelevant data so that you can build a useful data structure.

Notice that the first six (out of 59 total) contributors are named "theopolis", "marpaia", "javuto", "jedi22", "unixist", and "mofarrell". They have 553, 477, 104, 49, 30, 25 commits respectively.

![Screenshot](images/osquery_contributors.png)

To get a better of understanding of how this data is stored in the file, try searching through the raw data file for these usernames to look for any patterns. Your final dictionary should have 59 elements!

1\. Turn this data into a Python dictionary called `contributors` where the keys are the contributor names and the values are the number of commits that each contributor has.

In [89]:
import re # you might find this package useful

contributors = dict()

# Place your code here
file = open('/Users/monilshah/DataScienceCourse/ipython/hw/hw_1/data/osquery_contributors.html','r')
text = file.read()
find_regex="<a class=\"aname\".*?>(.+?)</a>"
find_regex1="<a class=\"cmt\".*?>(.+?)</a>"
pattern=re.compile(find_regex)
pattern1=re.compile(find_regex1)
keys=re.findall(pattern,text)
values=re.findall(pattern1,text)
for i in range(0,len(keys)):
        contributors[keys[i]]=values[i]       
# This line will print your dictionary for grading purposed. Do not remove this line!!!
print (contributors)
print ("\ntotal key-value pairs in dictionary: ",len(contributors))

{'theopolis': '553 commits', 'marpaia': '477 commits', 'javuto': '104 commits', 'jedi22': '49 commits', 'unixist': '30 commits', 'mofarrell': '25 commits', 'sharvilshah': '23 commits', 'lwhsu': '22 commits', 'wxsBSD': '20 commits', 'polachok': '14 commits', 'zwass': '14 commits', 'eastebry': '9 commits', 'maus-': '9 commits', 'vmauge': '8 commits', 'astanway': '6 commits', 'maclennann': '6 commits', 'blakefrantz': '6 commits', 'akshaydixi': '5 commits', 'arirubinstein': '4 commits', 'cdown': '4 commits', 'deniszh': '3 commits', 'achmiel': '3 commits', 'brandt': '3 commits', 'nlsun': '3 commits', 'mimeframe': '3 commits', 'mgoffin': '2 commits', 'mathieuk': '2 commits', 'ga2arch': '2 commits', 'glensc': '2 commits', 'jreese': '2 commits', 'Anubisss': '2 commits', 'timzimmermann': '2 commits', 'jamesgpearce': '2 commits', 'schettino72': '2 commits', 'castrapel': '2 commits', 'mlw': '2 commits', 'apage43': '1 commit', 'SimplyAhmazing': '1 commit', 'quad': '1 commit', 'yannick': '1 commit', 'blackfist': '1 commit', 'DavidGosselin': '1 commit', 'ecin': '1 commit', 'arubdesu': '1 commit', 'yetanotherhacker': '1 commit', 'rjeczalik': '1 commit', 'larzconwell': '1 commit', 'justintime32': '1 commit', 'alex': '1 commit', 'vlajos': '1 commit', 'dreid': '1 commit', 'kost': '1 commit', 'mtmcgrew': '1 commit', 'tburgin': '1 commit', 'mark-ignacio': '1 commit', 'shawndavenport': '1 commit', 'jacknagz': '1 commit', 'd0ugal': '1 commit', 'stevenhilder': '1 commit'}

total key-value pairs in dictionary:  59

### Part 3: Dealing with data Pythonically

In [8]:
# You might find these packages useful. You may import any others you want!
import pandas as pd
import numpy as np

1\. Load the data set `"data/ads_dataset.tsv"` into a Python Pandas data frame called `ads`.

In [25]:
# Place your code here
ads = pd.read_csv('/Users/monilshah/DataScienceCourse/ipython/hw/hw_1/data/ads_dataset.tsv',sep="\t")
ads.head().transpose()

                        NaN     NaN   NaN    NaN       NaN
isbuyer                 0.0     0.0   0.0    0.0    0.0000
buy_freq                NaN     NaN   NaN    NaN       NaN
visit_freq              1.0     1.0   1.0    1.0    2.0000
buy_interval            0.0     0.0   0.0    0.0    0.0000
sv_interval             0.0     0.0   0.0    0.0    0.5000
expected_time_buy       0.0     0.0   0.0    0.0    0.0000
expected_time_visit     0.0     0.0   0.0    0.0 -101.1493
last_buy              106.0    72.0   5.0    6.0  101.0000
last_visit            106.0    72.0   5.0    6.0  101.0000
multiple_buy            0.0     0.0   0.0    0.0    0.0000
multiple_visit          0.0     0.0   0.0    0.0    1.0000
uniq_urls             169.0   154.0   4.0  150.0  103.0000
num_checkins         2130.0  1100.0  12.0  539.0  362.0000
y_buy                   0.0     0.0   0.0    0.0    0.0000

2\. Write a Python function called `getDfSummary()` that does the following:
- Takes as input a data frame
- For each variable in the data frame calculates the following features:
  - `number_nan` to count the number of missing not-a-number values
  - Ignoring missing, NA, and Null values:
    - `number_distinct` to count the number of distinct values a variable can take on
    - `mean`, `max`, `min`, `std` (standard deviation), and `25%`, `50%`, `75%` to correspond to the appropriate percentiles
- All of these new features should be loaded in a new data frame. Each row of the data frame should be a variable from the input data frame, and the columns should be the new summary features.
- Returns this new data frame containing all of the summary information

Hint: The pandas `describe()` [(manual page)](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html) method returns a useful series of values that can be used here.

In [26]:
def getDfSummary(input_data):
    # Place your code here
    output_data= input_data.describe().transpose()
    output_data['number_nan']=input_data.isnull().sum()
    output_data['number_distinct']=input_data.apply(lambda x : len(x.unique()))
    return output_data

3\. How long does it take for your `getDfSummary()` function to work on your `ads` data frame? Show us the results below.

Hint: `%timeit getDfSummary(ads)`

In [27]:
# Place your code here
%timeit getDfSummary(ads)

10 loops, best of 3: 67.2 ms per loop

4\. Using the results returned from `getDfSummary()`, which fields, if any, contain missing `NaN` values?

In [28]:
# Place your code here
getDfSummary(ads)

,count,mean,std,min,25%,50%,75%,max,number_nan,number_distinct
isbuyer,54584.0,0.042632,0.202027,0.0000,0.0,0.0,0.000000,1.00000,0,2
buy_freq,2327.0,1.240653,0.782228,1.0000,1.0,1.0,1.000000,15.00000,52257,11
visit_freq,54584.0,1.852777,2.921820,0.0000,1.0,1.0,2.000000,84.00000,0,64
buy_interval,54584.0,0.210008,3.922016,0.0000,0.0,0.0,0.000000,174.62500,0,295
sv_interval,54584.0,5.825610,17.595442,0.0000,0.0,0.0,0.104167,184.91670,0,5886
expected_time_buy,54584.0,-0.198040,4.997792,-181.9238,0.0,0.0,0.000000,84.28571,0,348
expected_time_visit,54584.0,-10.210786,31.879722,-187.6156,0.0,0.0,0.000000,91.40192,0,15135
last_buy,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0,189
last_visit,54584.0,64.729335,53.476658,0.0000,18.0,51.0,105.000000,188.00000,0,189
multiple_buy,54584.0,0.006357,0.079479,0.0000,0.0,0.0,0.000000,1.00000,0,2
multiple_visit,54584.0,0.277444,0.447742,0.0000,0.0,0.0,1.000000,1.00000,0,2
uniq_urls,54584.0,86.569343,61.969765,-1.0000,30.0,75.0,155.000000,206.00000,0,207
num_checkins,54584.0,720.657592,1275.727306,1.0000,127.0,319.0,802.000000,37091.00000,0,4628
y_buy,54584.0,0.004635,0.067924,0.0000,0.0,0.0,0.000000,1.00000,0,2

Ans): buy_freq is the field with missing or NaN values

5\. For the fields with missing values, does it look like the data is missing at random? Are there any other fields that correlate perfectly, or predict that the data is missing? If missing, what should the data value be?

Hint: create another data frame that has just the records with a missing value. Get a summary of this data frame using `getDfSummary()` and compare the differences. Do some feature distributions change dramatically?

In [29]:
# Place your code here
null_data = ads[ads.isnull().any(axis=1)]
getDfSummary(null_data)

,count,mean,std,min,25%,50%,75%,max,number_nan,number_distinct
isbuyer,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0,1
buy_freq,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52257,1
visit_freq,52257.0,1.651549,2.147955,1.0000,1.0,1.0,2.000000,84.00000,0,48
buy_interval,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0,1
sv_interval,52257.0,5.686388,17.623555,0.0000,0.0,0.0,0.041667,184.91670,0,5112
expected_time_buy,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0,1
expected_time_visit,52257.0,-9.669298,31.239030,-187.6156,0.0,0.0,0.000000,91.40192,0,13351
last_buy,52257.0,65.741317,53.484622,0.0000,19.0,52.0,106.000000,188.00000,0,189
last_visit,52257.0,65.741317,53.484622,0.0000,19.0,52.0,106.000000,188.00000,0,189
multiple_buy,52257.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.00000,0,1
multiple_visit,52257.0,0.255602,0.436203,0.0000,0.0,0.0,1.000000,1.00000,0,2
uniq_urls,52257.0,86.656180,61.996711,-1.0000,30.0,75.0,155.000000,206.00000,0,207
num_checkins,52257.0,721.848518,1284.504018,1.0000,126.0,318.0,803.000000,37091.00000,0,4570
y_buy,52257.0,0.003024,0.054904,0.0000,0.0,0.0,0.000000,1.00000,0,2

Ans) : The field for which values are missing is buy_freq. The values in buy_freq are missing when the is_buyer value is 0 i.e the person is not buyer so it is not missing at random. So we can say is_buyer is the variable that correlates perfectly and decides whether data would be missing in buy_freq or not. The missing values should be 0. If not missing values should be number indicating frequency of buying.

6\. Which variables are binary?

In [30]:
# Place your code here
binary_vals = ads.dropna().isin([0,1]).all()
binary_vals

isbuyer                 True
buy_freq               False
visit_freq             False
buy_interval           False
sv_interval            False
expected_time_buy      False
expected_time_visit    False
last_buy               False
last_visit             False
multiple_buy            True
multiple_visit          True
uniq_urls              False
num_checkins           False
y_buy                   True
dtype: bool

Ans): As per the above results variables isbuyer , multiple_buy, multiple_visit , y_buy are binary variables.